services:
  - type: web
    name: flask-app
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install --upgrade pip
      pip install mediapipe==0.10.14
      pip install -r requirements.txt
    startCommand: gunicorn app:app
